### ISSUE TITLE
Firefox does not render URIs

### ISSUE THREAD

**Issue by ktk** [zazuko/data.admin.ch#2]
There is still something wrong with the rendering, Firefox does not render URIs on data.admin.ch

**Comment by retog** [comment]
Could you be a bit more specific? I see a lots of URI e.g. on http://classifications.data.admin.ch/municipalityversion/15042

**Comment by ktk** [comment]
Not sure what's going wrong on my side then, I still just see "Rendering results come here." and console reports the CORS issue:

    11:16:57.305 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://rawgit.com/rdf2h/rdf2h.github.io/master/2015/rdf2h-points.ttl. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>

**Comment by retog** [comment]
No Idea why you're getting the CORS exception and I don't, but rdf2h-points should be retrieved from cdn, I'll look into this ASAP.

**Comment by retog** [comment]
Fixed in trifid 12 days ago with: https://github.com/zazukoians/trifid-ld/commit/92f5cc5b38b379a622e6cf936f208e069c070889

**Comment by retog** [comment]
Things seems to be deployed in dockerhub, strange.

**Comment by ktk** [comment]
Then docker-compose does not pull correct image, will check manually. Updated the data.admin.ch docker image many times meanwhile.

**Comment by retog** [comment]
The images on the server seemed to be up-to-date, after triggering a new build for trifid I've tagged data.admin.ch so that a new build will be available shortly.

**Comment by ktk** [comment]
Super weird, still get the old link but in the code I see:

     data/templates/graph.html:        <link rel="matchers" href="//cdn.rawgit.com/rdf2h/rdf2h.github.io/v0.0.1/2015/rdf2h-points.ttl" type="text/turtle"/>

**Comment by ktk** [comment]
Now this is new, it does load it from cdn now but I still get the CORS error:

    12:42:14.799 Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://cdn.rawgit.com/rdf2h/rdf2h.github.io/v0.0.1/2015/rdf2h-points.ttl. (Reason: CORS header 'Access-Control-Allow-Origin' missing).1 <unknown>

I will do some more tests if I just get that with this particular firefox session. Doesn't seem to happen with the developer edition of Firefox.

**Comment by retog** [comment]
Closing for now as I cannot reproduce it and the link is now fixed.
